# Generated by Django 4.1.3 on 2023-06-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_items')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
    ]
